Allow overriding all Guzzle configuration settings
addwiki/mediawiki-api-base pull request #27
Opened 2017-01-21 19:33 UTC by c960657

This patch makes it possible to override all Guzzle configuration settings, not just user-agent and middleware.

2017-01-21 22:35 UTC, JeroenDeDauw commented on tests/unit/Guzzle/ClientFactoryTest.php
> +		$request = $this->getMockBuilder( 'Psr\Http\Message\RequestInterface' )->getMock();
You can use `RequestInterface:class`

2017-01-21 23:03 UTC, c960657 commented on tests/unit/Guzzle/ClientFactoryTest.php
> +		$request = $this->getMockBuilder( 'Psr\Http\Message\RequestInterface' )->getMock();
Done.

2017-01-23 08:00 UTC, addshore requested changes

2017-01-23 08:00 UTC, addshore commented on tests/unit/Guzzle/ClientFactoryTest.php
> + * @author Addshore
Am I the author of this class? ;)

2017-01-23 08:00 UTC, addshore commented on tests/unit/Guzzle/ClientFactoryTest.php
> + * @todo test interaction with logger
Again I think this comment was probably copied over in error, there isn't much interaction with the logger class in here to test!

2017-01-23 08:33 UTC, c960657 commented on tests/unit/Guzzle/ClientFactoryTest.php
> + * @todo test interaction with logger
Fixed :-)

2017-01-23 11:20 UTC, merged

2017-01-23 23:38 UTC, JeroenDeDauw commented on tests/unit/Guzzle/ClientFactoryTest.php
> + * @author Addshore
You are the one that will be blamed for bugs now ;)