Log warnings that are on the second level also
addwiki/mediawiki-api-base pull request #41
Opened 2017-12-18 23:29 UTC by Albert221

Bug: T177191

2017-12-19 01:01 UTC, samwilson requested changes
Thanks for working on this. A couple of comments.

Note that you could also add a new test, perhaps with the duplicate-upload warning as given in the ticket; that'd make sure this was fixed correctly. :-)

2017-12-19 01:01 UTC, samwilson commented on src/MediawikiApi.php
> +					// Accomodate both formatversion=2 and old-style API results
This section should not be duplicated from above. Instead, you could a new protected method `logWarning()` and call it from each of these places.

2017-12-19 01:01 UTC, samwilson commented on src/MediawikiApi.php
> +					return;
You're returning after the first iteration of the loop. What about if there are multiple warnings?

2017-12-19 01:01 UTC, samwilson commented on src/MediawikiApi.php
> +				if ( !array_key_exists( 'warnings', $value ) ) {
`$value` can be a string (see [test results](https://travis-ci.org/addwiki/mediawiki-api-base/jobs/318353872#L999)).

2017-12-20 00:20 UTC, samwilson requested changes
Looking good!

Just that little coding-standard fix that Travis is complaining about, and one minor comment.

2017-12-20 00:20 UTC, samwilson commented on src/MediawikiApi.php
> +	private function logWarning( $array ) {
This should be proteccted, in case subclasses want to do something different with it.

2017-12-20 02:12 UTC, samwilson approved these changes
Looks good to me. @addshore are you okay with this?

2017-12-20 10:22 UTC, addshore approved these changes

2017-12-20 10:22 UTC, merged